# Generated by Django 5.0.3 on 2024-06-11 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='watched',
            new_name='assistido',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='episodio',
            old_name='watched',
            new_name='assistido',
        ),
        migrations.RenameField(
            model_name='episodio',
            old_name='episode_number',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='description',
        ),
        migrations.AlterUniqueTogether(
            name='episodio',
            unique_together={('anime', 'numero')},
        ),
        migrations.RemoveField(
            model_name='episodio',
            name='title',
        ),
    ]
