# Generated by Django 5.0.3 on 2024-06-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_rename_watched_anime_assistido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='mal_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
